const KEY="unisched-v1";
const DEFAULT={settings:{university:"JOY UNIVERSITY",year:"2025–26",title:"TIME TABLE FOR THE ACADEMIC YEAR 2025-26",incharge:"Ms. S. AMBIKA",start:"09:00",duration:50,periods:8,days:["MON","TUE","WED","THU","FRI"],shortBreak:2,lunchBreak:5,breaks:[2,5]},departments:[{id:"SOCI",name:"School of Computational Intelligence",code:"SOCI"},{id:"SOET",name:"School of Engineering and Technology",code:"SOET"}],classes:[{id:"CSE3K",name:"B.Tech CSE – Year/Sem III/V",section:"K",department:"SOCI",room:"Room 103",incharge:"Ms. S. AMBIKA"}],sections:[{id:"SEC-K",name:"Section K",code:"K",department:"SOCI"}],faculty:[{id:"F1",name:"Dr. MARIYAPPAN KANDASAMY",department:"SOCI"},{id:"F2",name:"Dr. SOFIYA",department:"SOCI"},{id:"F3",name:"Ms. AMBIKA",department:"SOCI"},{id:"F4",name:"Dr. MANOJKUMAR",department:"SOCI"},{id:"F5",name:"MS. MARY DISILVA PRINCY",department:"SOCI"},{id:"F6",name:"NEW FACULTY 14",department:"SOCI"}],rooms:[{id:"R103",name:"Room 103",type:"Classroom",capacity:60,building:"Joveena Block"},{id:"CCL",name:"Cloud Computing Lab",type:"Lab",capacity:45,building:"Joveena Block"},{id:"SAK2",name:"SAK Seminar Hall 2nd Floor",type:"Seminar Hall",capacity:120,building:"SAK Block"}],courses:[
{id:"24BTCY151",code:"24BTCY151",name:"Introduction to Blockchain and Cryptocurrencty",l:3,t:0,p:0,credits:3,faculty:"F1",room:"R103"},
{id:"24BTCY152",code:"24BTCY152",name:"Malware Analysis",l:3,t:0,p:0,credits:3,faculty:"F1",room:"R103"},
{id:"24BTCY153",code:"24BTCY153",name:"Computer Architecture",l:3,t:0,p:0,credits:3,faculty:"F2",room:"R103"},
{id:"24BTCY154",code:"24BTCY154",name:"Software Engineering",l:3,t:0,p:0,credits:3,faculty:"F3",room:"R103"},
{id:"24BTCY155",code:"24BTCY155",name:"Criminology and Cyber Crimes",l:3,t:0,p:0,credits:3,faculty:"F4",room:"R103"},
{id:"24BTCY156",code:"24BTCY156",name:"Theory of Computation",l:3,t:1,p:0,credits:4,faculty:"F6",room:"R103"},
{id:"24BTCY851",code:"24BTCY851",name:"Principles of Management",l:3,t:0,p:0,credits:3,faculty:"F5",room:"R103"},
{id:"24BTCY251",code:"24BTCY251",name:"Introduction to Blockchain and Cryptocurrencty Lab",l:0,t:0,p:2,credits:1,faculty:"F1",room:"CCL",lab:true},
{id:"24BTCY252",code:"24BTCY252",name:"Malware Analysis Lab",l:0,t:0,p:2,credits:1,faculty:"F1",room:"CCL",lab:true}],
schedule:[
["MON",0,"24BTCY251","F1","CCL","CSE3K"],["MON",3,"24BTCY156","F6","R103","CSE3K"],["MON",4,"24BTCY153","F2","R103","CSE3K"],["MON",6,"24BTCY155","F4","R103","CSE3K"],
["TUE",0,"24BTCY152","F1","R103","CSE3K"],["TUE",1,"24BTCY151","F1","R103","CSE3K"],["TUE",3,"24BTCY156","F6","R103","CSE3K"],["TUE",4,"24BTCY851","F5","R103","CSE3K"],["TUE",6,"24BTCY155","F4","R103","CSE3K"],
["WED",0,"24BTCY151","F1","R103","CSE3K"],["WED",1,"24BTCY851","F5","R103","CSE3K"],["WED",3,"24BTCY153","F2","R103","CSE3K"],["WED",4,"24BTCY154","F3","R103","CSE3K"],["WED",6,"24BTCY156","F6","R103","CSE3K"],
["THU",0,"24BTCY851","F5","R103","CSE3K"],["THU",1,"24BTCY151","F1","R103","CSE3K"],["THU",3,"24BTCY153","F2","R103","CSE3K"],["THU",4,"24BTCY152","F1","R103","CSE3K"],["THU",6,"24BTCY154","F3","R103","CSE3K"],["THU",7,"24BTCY156","F6","R103","CSE3K"],
["FRI",0,"24BTCY252","F1","CCL","CSE3K"],["FRI",3,"24BTCY152","F1","R103","CSE3K"],["FRI",4,"24BTCY154","F3","R103","CSE3K"],["FRI",6,"24BTCY155","F4","R103","CSE3K"]]};
let db=load();
function load(){try{var x=JSON.parse(localStorage.getItem(KEY));if(!x)return copy(DEFAULT);x.settings=x.settings||copy(DEFAULT.settings);if(x.settings.shortBreak==null)x.settings.shortBreak=(x.settings.breaks&&x.settings.breaks[0]!=null?x.settings.breaks[0]:2);if(x.settings.lunchBreak==null)x.settings.lunchBreak=(x.settings.breaks&&x.settings.breaks[1]!=null?x.settings.breaks[1]:5);x.settings.breaks=[x.settings.shortBreak,x.settings.lunchBreak].filter(function(v,i,a){return v>=0&&v<x.settings.periods&&a.indexOf(v)===i});x.sections=x.sections||[];if(!x.sections.length){x.classes.forEach(function(c){if(c.section&&!x.sections.some(function(z){return z.code===c.section})){x.sections.push({id:"SEC-"+c.section,name:"Section "+c.section,code:c.section,department:c.department})}})}return x}catch(e){return copy(DEFAULT)}}
function copy(x){return JSON.parse(JSON.stringify(x))}
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function esc(x){return String(x==null?"":x).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function q(id){return document.getElementById(id)}
function course(id){return db.courses.find(function(x){return x.id===id})}
function fac(id){return db.faculty.find(function(x){return x.id===id})}
function room(id){return db.rooms.find(function(x){return x.id===id})}
function cl(id){return db.classes.find(function(x){return x.id===id})}
function dayLabel(d){return {MON:"Monday",TUE:"Tuesday",WED:"Wednesday",THU:"Thursday",FRI:"Friday",SAT:"Saturday"}[d]||d}
function breakType(p){if(p===db.settings.shortBreak)return "SHORT BREAK";if(p===db.settings.lunchBreak)return "LUNCH";return null}
function timeSlots(){var a=db.settings.start.split(":");var base=+a[0]*60 + +a[1];var out=[];for(var i=0;i<db.settings.periods;i++){var s=base+i*db.settings.duration,e=s+db.settings.duration;out.push({start:String(Math.floor(s/60)%24).padStart(2,"0")+":"+String(s%60).padStart(2,"0"),end:String(Math.floor(e/60)%24).padStart(2,"0")+":"+String(e%60).padStart(2,"0")})}return out}
function entry(day,p,classId){return db.schedule.find(function(x){return x[0]===day&&x[1]===p&&x[5]===classId})}
function nav(){document.querySelectorAll(".nav").forEach(function(b){b.onclick=function(){show(b.dataset.page)}});document.querySelectorAll("[data-go]").forEach(function(b){b.onclick=function(){show(b.dataset.go)}})}
function show(id){var page=q(id);if(!page)return;document.querySelectorAll(".page").forEach(function(p){p.classList.remove("active")});page.classList.add("active");document.querySelectorAll(".nav").forEach(function(n){n.classList.toggle("active",n.dataset.page===id)});q("title").textContent=id==="builder"?"Timetable Builder":id==="master"?"Master Setup":id.charAt(0).toUpperCase()+id.slice(1);renderAll()}
function options(arr,value,label){return arr.map(function(x){return "<option value='"+esc(x[value])+"'>"+esc(x[label])+"</option>"}).join("")}
function populate(){q("builderClass").innerHTML=options(db.classes,"id","name");q("classFilter").innerHTML=options(db.classes,"id","name");q("facultyFilter").innerHTML=options(db.faculty,"id","name");q("exportClass").innerHTML=options(db.classes,"id","name");q("exportFaculty").innerHTML=options(db.faculty,"id","name");q("exportCourse").innerHTML=options(db.courses,"id","name");q("exportDept").innerHTML=options(db.departments,"id","name")}
function tableForClass(id,editable){var currentClass=cl(id);if(!currentClass)return "<p class=\"muted\">Class not found.</p>";
 var ts=timeSlots(),h="<table class='timetable'><thead><tr><th>DAY</th>";
 ts.forEach(function(t){h+="<th>"+t.start+"<br>"+t.end+"</th>"});h+="</tr></thead><tbody>";
 db.settings.days.forEach(function(d){h+="<tr><th>"+dayLabel(d)+"</th>";for(var p=0;p<db.settings.periods;p++){var bt=breakType(p);if(bt){h+="<td class='slot break'>"+bt+"</td>";continue}var e=entry(d,p,id);var c=e&&course(e[2]);var f=e&&fac(e[3]);var r=e&&room(e[4]);var s=e&&c?"<strong>"+esc(c.code)+"</strong><span>"+esc(c.name)+"</span><span>"+esc(f?f.name:"Unknown faculty")+" · "+esc(r?r.name:"Unknown room")+"</span>":"<span>—</span>";h+="<td class='slot "+(c&&c.lab?"lab ":"")+(editable?"editable":"")+"' "+(editable?"data-day='"+d+"' data-period='"+p+"'":"")+">"+s+"</td>"}h+="</tr>"});return h+"</tbody></table>"}
function masterCalendarUI(){var days=q("masterDays");if(!days)return;q("masterDays").value=db.settings.days.join(",");q("masterPeriods").value=db.settings.periods;q("masterStart").value=db.settings.start;q("masterDuration").value=db.settings.duration;var opts="<option value='-1'>None</option>";for(var i=0;i<db.settings.periods;i++)opts+="<option value='"+i+"'>Period "+(i+1)+"</option>";q("masterShortBreak").innerHTML=opts;q("masterLunchBreak").innerHTML=opts;q("masterShortBreak").value=db.settings.shortBreak==null?-1:db.settings.shortBreak;q("masterLunchBreak").value=db.settings.lunchBreak==null?-1:db.settings.lunchBreak}
function master(){if(!q("masterClassList"))return;populateMaster();masterCalendarUI();q("masterClassList").innerHTML=db.classes.map(function(c){var sec=db.sections.find(function(s){return s.code===c.section});return "<div class='card'><b>"+esc(c.name)+"</b><span>Section "+esc(c.section)+" · "+esc(sec?sec.name:"")+" · "+esc(c.room)+" · "+esc(c.incharge)+"</span></div>"}).join("")||"<p class='muted'>No classes configured.</p>";q("masterPeopleList").innerHTML=db.sections.map(function(x){return "<div class='card'><b>"+esc(x.name)+"</b><span>"+esc(x.code)+" · "+esc((db.departments.find(function(d){return d.id===x.department})||{}).name||"")+"</span></div>"}).join("")+db.faculty.map(function(x){return "<div class='card'><b>"+esc(x.name)+"</b><span>Faculty · "+esc((db.departments.find(function(d){return d.id===x.department})||{}).name||"")+"</span></div>"}).join("")}
function populateMaster(){if(!q("masterDept"))return;q("masterDept").innerHTML=options(db.departments,"id","name");q("masterSection").innerHTML=options(db.sections,"id","name");q("masterClass").innerHTML=options(db.classes,"id","name");q("masterFaculty").innerHTML=options(db.faculty,"id","name");q("masterCourse").innerHTML=options(db.courses,"id","name")}
function builder(){var id=q("builderClass").value;if(!id){q("builderTable").innerHTML="<p>No class configured.</p>";return}q("builderTable").innerHTML=tableForClass(id,true);q("builderTable").querySelectorAll(".editable").forEach(function(td){td.onclick=function(){editSlot(td.dataset.day,+td.dataset.period)}});var used={};db.courses.forEach(function(c){used[c.id]=0});db.schedule.filter(function(x){return x[5]===id}).forEach(function(x){used[x[2]]++});var html="";db.courses.forEach(function(c){var req=(c.l||0)+(c.t||0)+(c.p||0),got=used[c.id]||0;if(!req)return;html+="<div class='load'><div><b>"+esc(c.code)+"</b><br>"+esc(c.name)+"</div><span>"+got+"/"+req+"</span><div class='bar'><i style='width:"+Math.min(100,req?got/req*100:0)+"%'></i></div></div>"});q("workload").innerHTML=html||"<p class='muted'>No courses.</p>";var cc=conflicts().filter(function(x){return x.classId===id}).length;q("conflicts").textContent=cc+" conflicts";q("conflicts").className="badge "+(cc?"bad":"good")}
function editSlot(day,p){var id=q("builderClass").value,e=entry(day,p,id);if(breakType(p))return;var html="<label>Course<select name='course'><option value=''>Empty slot</option>"+options(db.courses,"id","name")+"</select></label><label>Room<select name='room'>"+options(db.rooms,"id","name")+"</select></label><div class='actions'><button type='button' id='cancelModal'>Cancel</button><button class='primary'>Save slot</button></div>";openModal("Edit timetable slot",html);var f=q("modalForm");f.course.value=e?e[2]:"";f.room.value=e?e[4]:(course(db.courses[0].id)||{}).room||db.rooms[0].id;q("cancelModal").onclick=closeModal;f.onsubmit=function(ev){ev.preventDefault();db.schedule=db.schedule.filter(function(x){return !(x[0]===day&&x[1]===p&&x[5]===id)});if(f.course.value){var c=course(f.course.value);db.schedule.push([day,p,c.id,c.faculty,f.room.value,id])}closeModal();save()}}
function autoGenerate(){var id=q("builderClass").value;if(!id)return;db.schedule=db.schedule.filter(function(x){return x[5]!==id});var slots=[];db.settings.days.forEach(function(d){for(var p=0;p<db.settings.periods;p++)if(!breakType(p))slots.push([d,p])});var needs=[];db.courses.forEach(function(c){var n=c.lab?Math.ceil((c.p||0)/2):((c.l||0)+(c.t||0)+(c.p||0));for(var i=0;i<n;i++)needs.push(c)});needs.sort(function(a,b){return (b.lab?1:0)-(a.lab?1:0)});needs.forEach(function(c){for(var i=0;i<slots.length;i++){var d=slots[i][0],p=slots[i][1];if(entry(d,p,id))continue;if(db.schedule.some(function(x){return x[0]===d&&x[1]===p&&x[3]===c.faculty}))continue;if(db.schedule.some(function(x){return x[0]===d&&x[1]===p&&x[4]===c.room}))continue;if(c.lab){var np=p+1;if(np>=db.settings.periods||breakType(np)||entry(d,np,id))continue;if(db.schedule.some(function(x){return x[0]===d&&x[1]===np&&x[3]===c.faculty}))continue;if(db.schedule.some(function(x){return x[0]===d&&x[1]===np&&x[4]===c.room}))continue;db.schedule.push([d,p,c.id,c.faculty,c.room,id]);db.schedule.push([d,np,c.id,c.faculty,c.room,id]);break}db.schedule.push([d,p,c.id,c.faculty,c.room,id]);break}});save()}
function clearClass(){var id=q("builderClass").value;if(confirm("Clear this class timetable?")){db.schedule=db.schedule.filter(function(x){return x[5]!==id});save()}}
function conflicts(){var out=[];db.schedule.forEach(function(x,i){db.schedule.forEach(function(y,j){if(i>=j||x[0]!==y[0]||x[1]!==y[1])return;if(x[5]===y[5])out.push({classId:x[5],type:"Class",day:x[0],period:x[1]});if(x[3]===y[3])out.push({classId:x[5],type:"Faculty",day:x[0],period:x[1]});if(x[4]===y[4])out.push({classId:x[5],type:"Room",day:x[0],period:x[1]})})});return out.filter(function(x,i,a){return a.findIndex(function(y){return JSON.stringify(x)===JSON.stringify(y)})===i})}
function dashboard(){q("year").textContent=db.settings.year;q("days").textContent=db.settings.days.length;q("periods").textContent=db.settings.periods;q("stats").innerHTML=[["Classes",db.classes.length],["Courses",db.courses.length],["Faculty",db.faculty.length],["Rooms",db.rooms.length]].map(function(x){return "<div class='stat'><span>"+x[0]+"</span><strong>"+x[1]+"</strong></div>"}).join("");q("dashTable").innerHTML=db.classes[0]?tableForClass(db.classes[0].id,false):"<p class='muted'>Add a class.</p>";var c=conflicts();q("checks").innerHTML="<div class='check'><b>Schedule records</b><span>"+db.schedule.length+" sessions stored</span></div><div class='check'><b>Hard conflicts</b><span>"+(c.length?c.length+" conflicts":"No collisions detected")+"</span></div><div class='check'><b>Exports</b><span>PDF, Excel, CSV, Word, PNG, JSON and print</span></div>"}
function classes(){q("classTable").innerHTML=tableForClass(q("classFilter").value||db.classes[0].id,false)}
function faculty(){var id=q("facultyFilter").value||db.faculty[0].id,html="<table><thead><tr><th>DAY</th>";timeSlots().forEach(function(t){html+="<th>"+t.start+"<br>"+t.end+"</th>"});html+="</tr></thead><tbody>";db.settings.days.forEach(function(d){html+="<tr><th>"+dayLabel(d)+"</th>";for(var p=0;p<db.settings.periods;p++){var e=db.schedule.find(function(x){return x[0]===d&&x[1]===p&&x[3]===id});html+=e?"<td><b>"+e[2]+"</b><br>"+esc(cl(e[5]).section)+"</td>":"<td>—</td>"}html+="</tr>"});q("facultyTable").innerHTML=html+"</tbody></table>"}
function courses(){var h="<table><thead><tr><th>S.No</th><th>Code</th><th>Subject</th><th>L</th><th>T</th><th>P</th><th>Hrs/Wk</th><th>Credits</th><th>Faculty</th><th>Room</th></tr></thead><tbody>";db.courses.forEach(function(c,i){var f=fac(c.faculty),r=room(c.room);h+="<tr><td>"+(i+1)+"</td><td><b>"+esc(c.code)+"</b></td><td>"+esc(c.name)+"</td><td>"+(c.l||0)+"</td><td>"+(c.t||0)+"</td><td>"+(c.p||0)+"</td><td>"+((c.l||0)+(c.t||0)+(c.p||0))+"</td><td>"+c.credits+"</td><td>"+esc(f?f.name:"—")+"</td><td>"+esc(r?r.name:"—")+"</td></tr>"});q("courseTable").innerHTML=h+"</tbody></table>"}
function rooms(){var h="<table><thead><tr><th>Room</th><th>Type</th><th>Capacity</th><th>Building</th><th>Sessions</th></tr></thead><tbody>";db.rooms.forEach(function(r){h+="<tr><td><b>"+esc(r.name)+"</b></td><td>"+esc(r.type)+"</td><td>"+r.capacity+"</td><td>"+esc(r.building)+"</td><td>"+db.schedule.filter(function(x){return x[4]===r.id}).length+"</td></tr>"});q("roomTable").innerHTML=h+"</tbody></table>"}
function departments(){q("deptList").innerHTML=db.departments.map(function(d){return "<div class='card'><b>"+esc(d.name)+"</b><span>"+d.code+" · "+db.classes.filter(function(c){return c.department===d.id}).length+" classes · "+db.faculty.filter(function(f){return f.department===d.id}).length+" faculty</span></div>"}).join("");q("sectionList").innerHTML=db.classes.map(function(c){return "<div class='card'><b>"+esc(c.name)+" — Section "+esc(c.section)+"</b><span>"+esc(c.room)+" · In-charge: "+esc(c.incharge)+"</span></div>"}).join("")}
function settingsUI(){q("sUniversity").value=db.settings.university;q("sYear").value=db.settings.year;q("sTitle").value=db.settings.title;q("sIncharge").value=db.settings.incharge;q("sDays").value=db.settings.days.join(",");q("sStart").value=db.settings.start;q("sDuration").value=db.settings.duration;q("sPeriods").value=db.settings.periods}
function renderAll(){populate();dashboard();master();builder();classes();faculty();courses();rooms();departments();settingsUI()}
function openModal(title,html){q("modalTitle").textContent=title;q("modalForm").innerHTML=html;q("modal").classList.add("open")}
function closeModal(){q("modal").classList.remove("open")}
function addFaculty(){openModal("Add Faculty","<label>Faculty name<input name='name' required></label><label>Department<select name='department'>"+options(db.departments,"id","name")+"</select></label><div class='actions'><button type='button' id='cancelModal'>Cancel</button><button class='primary'>Add Faculty</button></div>");q("cancelModal").onclick=closeModal;q("modalForm").onsubmit=function(e){e.preventDefault();var f=new FormData(e.target);db.faculty.push({id:"F"+Date.now(),name:f.get("name"),department:f.get("department")});closeModal();save()}}
function addSection(){openModal("Add Section","<label>Section name<input name='name' placeholder='Section A' required></label><label>Section code<input name='code' placeholder='A' required></label><label>Department<select name='department'>"+options(db.departments,"id","name")+"</select></label><div class='actions'><button type='button' id='cancelModal'>Cancel</button><button class='primary'>Add Section</button></div>");q("cancelModal").onclick=closeModal;q("modalForm").onsubmit=function(e){e.preventDefault();var f=new FormData(e.target),code=f.get("code").toUpperCase();db.sections.push({id:"SEC-"+code+"-"+Date.now(),name:f.get("name"),code:code,department:f.get("department")});closeModal();save()}}
function addClass(){openModal("Add Class","<label>Class name<input name='name' placeholder='B.Tech CSE – Year/Sem III/V' required></label><label>Section<select name='section'>"+options(db.sections,"code","name")+"</select></label><label>Department<select name='department'>"+options(db.departments,"id","name")+"</select></label><label>Room<select name='room'>"+options(db.rooms,"id","name")+"</select></label><label>Class in-charge<input name='incharge'></label><div class='actions'><button type='button' id='cancelModal'>Cancel</button><button class='primary'>Add Class</button></div>");q("cancelModal").onclick=closeModal;q("modalForm").onsubmit=function(e){e.preventDefault();var f=new FormData(e.target),id="CLS-"+Date.now();db.classes.push({id:id,name:f.get("name"),section:f.get("section"),department:f.get("department"),room:f.get("room"),incharge:f.get("incharge")});closeModal();save()}}
function addCourse(){openModal("Add Course","<label>Course code<input name='code' required></label><label>Subject name<input name='name' required></label><div class='formgrid'><label>Lectures<input name='l' type='number' value='3'></label><label>Tutorials<input name='t' type='number' value='0'></label><label>Practicals<input name='p' type='number' value='0'></label><label>Credits<input name='credits' type='number' value='3'></label></div><label>Faculty<select name='faculty'>"+options(db.faculty,"id","name")+"</select></label><label>Room<select name='room'>"+options(db.rooms,"id","name")+"</select></label><div class='actions'><button type='button' id='cancelModal'>Cancel</button><button class='primary'>Add</button></div>");q("cancelModal").onclick=closeModal;q("modalForm").onsubmit=function(e){e.preventDefault();var f=new FormData(e.target);db.courses.push({id:f.get("code"),code:f.get("code"),name:f.get("name"),l:+f.get("l"),t:+f.get("t"),p:+f.get("p"),credits:+f.get("credits"),faculty:f.get("faculty"),room:f.get("room")});closeModal();save()}}
function addRoom(){openModal("Add Room","<label>Room name<input name='name' required></label><label>Type<input name='type' value='Classroom'></label><label>Capacity<input name='capacity' type='number' value='60'></label><label>Building<input name='building'></label><div class='actions'><button type='button' id='cancelModal'>Cancel</button><button class='primary'>Add</button></div>");q("cancelModal").onclick=closeModal;q("modalForm").onsubmit=function(e){e.preventDefault();var f=new FormData(e.target);db.rooms.push({id:"R"+Date.now(),name:f.get("name"),type:f.get("type"),capacity:+f.get("capacity"),building:f.get("building")});closeModal();save()}}
function addDept(){openModal("Add Department","<label>Department name<input name='name' required></label><label>Code<input name='code' required></label><div class='actions'><button type='button' id='cancelModal'>Cancel</button><button class='primary'>Add</button></div>");q("cancelModal").onclick=closeModal;q("modalForm").onsubmit=function(e){e.preventDefault();var f=new FormData(e.target),code=f.get("code").toUpperCase();db.departments.push({id:code,name:f.get("name"),code:code});closeModal();save()}}
function csvRows(){var rows=[];db.schedule.forEach(function(x){rows.push({Day:x[0],Period:x[1]+1,Time:timeSlots()[x[1]].start+" - "+timeSlots()[x[1]].end,Class:cl(x[5]).name,Section:cl(x[5]).section,Course:x[2],Subject:course(x[2]).name,Faculty:fac(x[3]).name,Room:room(x[4]).name})});return rows}
function download(name,data,type){var b=new Blob([data],{type:type}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(a.href)},500)}
function exportCSV(){var rows=csvRows(),keys=Object.keys(rows[0]||{Day:""}),out=keys.join(",")+"\\n"+rows.map(function(r){return keys.map(function(k){return '"'+String(r[k]||"").replaceAll('"','""')+'"'}).join(",")}).join("\\n");download("university-timetable.csv",out,"text/csv")}
function exportExcel(){var wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(csvRows()),"Schedule");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(db.courses),"Courses");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(db.faculty),"Faculty");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(db.rooms),"Rooms");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(db.classes),"Classes");XLSX.writeFile(wb,"university-timetable.xlsx")}
function exportWord(){var rows=csvRows(),html="<html><head><meta charset='utf-8'><style>body{font-family:Arial}table{border-collapse:collapse;width:100%;font-size:10px}td,th{border:1px solid #555;padding:5px}th{background:#eee}</style></head><body><h2>"+esc(db.settings.university)+"</h2><h3>"+esc(db.settings.title)+"</h3><table><tr>"+Object.keys(rows[0]).map(function(k){return "<th>"+esc(k)+"</th>"}).join("")+"</tr>"+rows.map(function(r){return "<tr>"+Object.keys(rows[0]).map(function(k){return "<td>"+esc(r[k])+"</td>"}).join("")+"</tr>"}).join("")+"</table></body></html>";download("university-timetable.doc",html,"application/msword")}
async function exportPNG(){var el=q("dashTable"),canvas=await html2canvas(el,{scale:2,backgroundColor:"#fff"});canvas.toBlob(function(b){downloadBlob("class-timetable.png",b)})}
function downloadBlob(name,b){var a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;document.body.appendChild(a);a.click();a.remove()}
async function exportPDF(all){var ids=all?db.classes.map(function(c){return c.id}):[q("exportClass").value||db.classes[0].id];var js=window.jspdf.jsPDF,pdf=new js({orientation:"landscape",unit:"mm",format:"a4"});for(var i=0;i<ids.length;i++){var temp=document.createElement("div");temp.style.cssText="position:fixed;left:-10000px;top:0;width:1100px;background:#fff;padding:30px;font-family:Arial";temp.innerHTML="<h2 style='text-align:center'>"+esc(db.settings.university)+"</h2><h3 style='text-align:center'>"+esc(db.settings.title)+"</h3><p style='text-align:center'>"+esc(cl(ids[i]).name)+" — Section "+esc(cl(ids[i]).section)+" | "+esc(cl(ids[i]).room)+"</p>"+tableForClass(ids[i],false);document.body.appendChild(temp);var canvas=await html2canvas(temp,{scale:2,backgroundColor:"#fff"});if(i)pdf.addPage();pdf.addImage(canvas.toDataURL("image/png"),"PNG",8,8,281,Math.min(190,281*canvas.height/canvas.width));temp.remove()}pdf.save(all?"all-university-timetables.pdf":"class-timetable.pdf")}
function backup(){download("unischedule-backup.json",JSON.stringify(db,null,2),"application/json")}
function exportAction(type){if(type==="json")return backup();if(type==="csv")return exportCSV();if(type==="excel")return exportExcel();if(type==="word")return exportWord();if(type==="png")return exportPNG();if(type==="pdf")return exportPDF(false);if(type==="allpdf")return exportPDF(true);if(type==="print")return window.print()}
function saveMasterCalendar(){var days=q("masterDays").value.split(",").map(function(x){return x.trim().toUpperCase()}).filter(Boolean);var periods=Math.max(1,Math.min(16,+q("masterPeriods").value||8));var sb=+q("masterShortBreak").value,lb=+q("masterLunchBreak").value;if(sb>=periods)sb=-1;if(lb>=periods)lb=-1;if(sb>=0&&lb>=0&&sb===lb){alert("Short break and lunch break must use different periods.");return}db.settings.days=days;db.settings.periods=periods;db.settings.start=q("masterStart").value||"09:00";db.settings.duration=Math.max(1,+q("masterDuration").value||50);db.settings.shortBreak=sb;db.settings.lunchBreak=lb;db.settings.breaks=[sb,lb].filter(function(v){return v>=0});save()}
function bind(){nav();q("backup").onclick=backup;q("quick").onclick=function(){show("builder");autoGenerate()};q("generate").onclick=autoGenerate;q("clearClass").onclick=clearClass;q("builderClass").onchange=builder;q("masterAddClass").onclick=addClass;q("masterAddSection").onclick=addSection;q("masterAddFaculty").onclick=addFaculty;q("masterAddCourse").onclick=addCourse;q("masterAddDept").onclick=addDept;q("saveMasterCalendar").onclick=saveMasterCalendar;q("classFilter").onchange=classes;q("facultyFilter").onchange=faculty;q("addCourse").onclick=addCourse;q("addRoom").onclick=addRoom;q("addDept").onclick=addDept;q("closeModal").onclick=closeModal;q("modal").onclick=function(e){if(e.target.id==="modal")closeModal()};document.querySelectorAll(".export").forEach(function(b){b.onclick=function(){exportAction(b.dataset.type)}});document.querySelectorAll(".exportCard").forEach(function(b){b.onclick=function(){exportAction(b.dataset.type)}});q("saveSettings").onclick=function(){db.settings.university=q("sUniversity").value;db.settings.year=q("sYear").value;db.settings.title=q("sTitle").value;db.settings.incharge=q("sIncharge").value;save()};q("saveCalendar").onclick=function(){db.settings.days=q("sDays").value.split(",").map(function(x){return x.trim().toUpperCase()}).filter(Boolean);db.settings.start=q("sStart").value;db.settings.duration=+q("sDuration").value;db.settings.periods=Math.max(1,+q("sPeriods").value);if(db.settings.shortBreak>=db.settings.periods)db.settings.shortBreak=-1;if(db.settings.lunchBreak>=db.settings.periods)db.settings.lunchBreak=-1;db.settings.breaks=[db.settings.shortBreak,db.settings.lunchBreak].filter(function(v){return v>=0});save()};q("reset").onclick=function(){if(confirm("Reset the workspace to the supplied sample?")){db=copy(DEFAULT);save()}}}
bind();renderAll();